//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangVatLieuXayDung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAIVIET
    {
        public int MABV { get; set; }
        public string ID { get; set; }
        public string TIEUDE { get; set; }
        public Nullable<System.DateTime> NGAYDANG { get; set; }
        public string NOIDUNG { get; set; }
    
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
