//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangVatLieuXayDung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHGIA
    {
        public int MADG { get; set; }
        public string SANPHAM { get; set; }
        public Nullable<System.DateTime> THOIGIAN { get; set; }
        public string NOIDUNG { get; set; }
    
        public virtual SANPHAM SANPHAM1 { get; set; }
    }
}
