//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangVatLieuXayDung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIOHANG
    {
        public int MAGH { get; set; }
        public string MAKH { get; set; }
        public string MASP { get; set; }
        public string TENSP { get; set; }
        public string SOLUONG { get; set; }
        public string DONVITINH { get; set; }
        public Nullable<decimal> DONGIA { get; set; }
        public Nullable<decimal> THANHTIEN { get; set; }
        public string ANH { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
